name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    # don't run on pushes to forks
    if: github.event_name == 'pull_request' || github.repository == 'bensteinberg/actions-test'

    steps:
      - uses: actions/checkout@v2

      - name: Rebuild docker images
        id: rebuild
        uses: harvard-lil/docker-compose-update-action@main

      - name: docker compose up
        run: |
          # --ignore-pull-failures for PRs with new images
          # that haven't been pushed yet:
          docker compose -f docker-compose.yml pull --ignore-pull-failures || true
          docker compose -f docker-compose.yml up -d

      - name: Show running containers
        run: docker ps -a

      - name: Show logs
        run: docker compose logs

      - name: Run test suite
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'  # avoid docker-compose "the input device is not a TTY" -- see https://github.com/actions/runner/issues/241#issuecomment-842566950
        run: docker compose exec web ls /app

      - name: Update image tag in git
        if: github.event_name == 'push'
        run: |
          git config user.email "bsteinberg@law.harvard.edu"
          git config user.name "Github Actions"
          if [[ `git status docker-compose.yml docker-compose.override.yml --porcelain` ]] ; then
            git add docker-compose.yml docker-compose.override.yml
            git commit -m "Bump image version [skip ci]"
            git push origin develop || exit 1
          fi

      - name: Push docker images
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: harvard-lil/docker-compose-update-action@main
        with:
          registry: "registry.lil.tools"
          registry-user: ${{ secrets.REPOSITORY_USER }}
          registry-pass: ${{ secrets.REPOSITORY_TOKEN }}
          bake-action: "push"
